[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.15.4"
hooks = [
  { id = "ruff-check", args = ["--fix"], types_or = ["python", "pyi"] },
  { id = "ruff-format", types_or = ["python", "pyi"] },
]